### ISSUE TITLE
Socket programming with Java

### ISSUE THREAD

**Issue by apondi-911** [section-io/docs#145]
socket programming with Java is used for communication for applications running in Java Runtime Environment JRE.
It is a way of connecting two nodes on a network. This tutorial will illustrate how to two nodes on a network are able to communicate with Java

**Comment by ninjaginja** [comment]
Hello @apondi-911. Could you please clarify this issue that you opened in Section's docs? Are you suggesting that we add this to our documentation at https://www.section.io/docs/?

Alternatively, if you are trying to submit a topic for review for our Engineering Education program, that is done in this repo: https://github.com/section-engineering-education/engineering-education
